/**
 * Main JavaScript file for Rhetoric & AI website
 * Handles general utilities and initialization
 */

// Wait for DOM to be fully loaded
document.addEventListener('DOMContentLoaded', function() {
    console.log('Rhetoric & AI website loaded successfully');

    // Initialize smooth scrolling for anchor links
    initSmoothScrolling();

    // Add intersection observer for scroll animations
    initScrollAnimations();
});

/**
 * Initialize smooth scrolling for internal anchor links
 */
function initSmoothScrolling() {
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function(e) {
            e.preventDefault();
            const target = document.querySelector(this.getAttribute('href'));
            if (target) {
                target.scrollIntoView({
                    behavior: 'smooth',
                    block: 'start'
                });
            }
        });
    });
}

/**
 * Initialize intersection observer for scroll-triggered animations
 */
function initScrollAnimations() {
    const observerOptions = {
        threshold: 0.1,
        rootMargin: '0px 0px -50px 0px'
    };

    const observer = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                entry.target.classList.add('fade-in');
                observer.unobserve(entry.target);
            }
        });
    }, observerOptions);

    // Observe cards and sections
    document.querySelectorAll('.module-card, .assignment-card, .debate-card, .resource-card').forEach(el => {
        observer.observe(el);
    });
}

/**
 * Utility function to create and open worksheet in new window
 */
function openWorksheet(worksheetId) {
    const worksheets = {
        worksheet1: generateWorksheet1(),
        worksheet2: generateWorksheet2(),
        worksheet3: generateWorksheet3()
    };

    const content = worksheets[worksheetId];
    if (!content) {
        console.error('Worksheet not found:', worksheetId);
        return;
    }

    const printWindow = window.open('', '_blank');
    printWindow.document.write(content);
    printWindow.document.close();
}

/**
 * Generate Worksheet 1: Rhetorical Analysis Framework for AI-Generated Text
 */
function generateWorksheet1() {
    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rhetorical Analysis Framework for AI-Generated Text</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; }
        h1 { color: #3b82f6; border-bottom: 3px solid #3b82f6; padding-bottom: 10px; }
        h2 { color: #2563eb; margin-top: 30px; }
        .section { background: #f9fafb; padding: 20px; margin: 20px 0; border-left: 4px solid #3b82f6; }
        .question { margin: 15px 0; }
        .question strong { color: #1f2937; }
        .answer-space { border-bottom: 1px solid #ccc; min-height: 60px; margin-top: 5px; }
        @media print { body { margin: 20px; } .no-print { display: none; } }
    </style>
</head>
<body>
    <h1>Rhetorical Analysis Framework for AI-Generated Text</h1>
    <p><strong>Name:</strong> _____________________________ <strong>Date:</strong> _____________________</p>

    <div class="section">
        <h2>Part 1: Context & Source</h2>
        <div class="question">
            <strong>1. What is the text being analyzed?</strong>
            <div class="answer-space"></div>
        </div>
        <div class="question">
            <strong>2. Was this text generated by AI, human, or collaboration? How do you know?</strong>
            <div class="answer-space"></div>
        </div>
        <div class="question">
            <strong>3. What was the prompt or context that generated this text?</strong>
            <div class="answer-space"></div>
        </div>
    </div>

    <div class="section">
        <h2>Part 2: Rhetorical Appeals Analysis</h2>
        <div class="question">
            <strong>Ethos (Credibility/Authority):</strong><br>
            How does the text establish credibility? What sources, expertise, or authority does it claim or reference?
            <div class="answer-space"></div>
        </div>
        <div class="question">
            <strong>Pathos (Emotional Appeal):</strong><br>
            What emotions does the text evoke? What language, examples, or narratives create emotional resonance?
            <div class="answer-space"></div>
        </div>
        <div class="question">
            <strong>Logos (Logic/Evidence):</strong><br>
            What logical arguments or evidence does the text present? How is reasoning structured?
            <div class="answer-space"></div>
        </div>
    </div>

    <div class="section">
        <h2>Part 3: AI-Specific Considerations</h2>
        <div class="question">
            <strong>4. What rhetorical patterns typical of AI do you notice?</strong><br>
            (e.g., hedging language, balanced perspectives, generic phrasing, lack of lived experience)
            <div class="answer-space"></div>
        </div>
        <div class="question">
            <strong>5. What biases or limitations might be present due to AI training data?</strong>
            <div class="answer-space"></div>
        </div>
        <div class="question">
            <strong>6. How might the algorithmic nature of AI affect the rhetorical choices made?</strong>
            <div class="answer-space"></div>
        </div>
    </div>

    <div class="section">
        <h2>Part 4: Effectiveness & Reflection</h2>
        <div class="question">
            <strong>7. For what audience and purpose is this text effective or ineffective? Why?</strong>
            <div class="answer-space"></div>
        </div>
        <div class="question">
            <strong>8. What would you change to improve the rhetorical effectiveness?</strong>
            <div class="answer-space"></div>
        </div>
        <div class="question">
            <strong>9. What does this analysis teach you about using AI for rhetorical tasks?</strong>
            <div class="answer-space"></div>
        </div>
    </div>

    <button class="no-print" onclick="window.print()" style="background: #3b82f6; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; margin: 20px 0;">Print Worksheet</button>
</body>
</html>
    `;
}

/**
 * Generate Worksheet 2: Effective Prompting Guide
 */
function generateWorksheet2() {
    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Effective Prompting Guide for Rhetorical Analysis</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; }
        h1 { color: #3b82f6; border-bottom: 3px solid #3b82f6; padding-bottom: 10px; }
        h2 { color: #2563eb; margin-top: 30px; }
        .section { background: #f9fafb; padding: 20px; margin: 20px 0; border-left: 4px solid #8b5cf6; }
        .example { background: #fff; padding: 15px; margin: 10px 0; border-radius: 5px; border: 1px solid #e5e7eb; }
        .good { border-left: 4px solid #10b981; }
        .bad { border-left: 4px solid #ef4444; }
        .template { background: #dbeafe; padding: 15px; margin: 10px 0; border-radius: 5px; font-family: monospace; }
        @media print { body { margin: 20px; } .no-print { display: none; } }
    </style>
</head>
<body>
    <h1>Effective Prompting Guide for Rhetorical Analysis</h1>
    <p><strong>Name:</strong> _____________________________ <strong>Date:</strong> _____________________</p>

    <div class="section">
        <h2>Prompting Principles</h2>
        <p><strong>Be Specific:</strong> Clearly state what rhetorical framework or concepts you want the AI to use.</p>
        <p><strong>Provide Context:</strong> Include information about audience, purpose, and situation.</p>
        <p><strong>Set Constraints:</strong> Specify length, format, and level of detail.</p>
        <p><strong>Iterate:</strong> Ask follow-up questions to refine and deepen the analysis.</p>
    </div>

    <div class="section">
        <h2>Weak vs. Strong Prompts</h2>

        <div class="example bad">
            <strong>❌ Weak:</strong> "Analyze this text."
            <p><em>Problem: Too vague, no framework specified</em></p>
        </div>

        <div class="example good">
            <strong>✓ Strong:</strong> "Using Aristotelian rhetorical appeals (ethos, pathos, logos), analyze how this political speech persuades its audience. Identify specific passages for each appeal and evaluate their effectiveness."
            <p><em>Why it works: Specific framework, clear task, structured output requested</em></p>
        </div>

        <div class="example bad">
            <strong>❌ Weak:</strong> "Is this argument good?"
            <p><em>Problem: Subjective, no criteria specified</em></p>
        </div>

        <div class="example good">
            <strong>✓ Strong:</strong> "Evaluate this argument using the Toulmin model. Identify the claim, grounds, warrant, backing, and qualifiers. Assess the strength of each component and identify any missing elements."
            <p><em>Why it works: Specific analytical framework, structured approach</em></p>
        </div>
    </div>

    <div class="section">
        <h2>Prompt Templates</h2>

        <h3>Template 1: Basic Rhetorical Analysis</h3>
        <div class="template">
Analyze [TEXT/SPEECH] using [RHETORICAL FRAMEWORK].

For each element of the framework, provide:
1. Specific examples from the text
2. Explanation of the rhetorical strategy
3. Evaluation of effectiveness for [TARGET AUDIENCE]

Consider the rhetorical situation: [CONTEXT/PURPOSE/CONSTRAINTS]
        </div>

        <h3>Template 2: Comparative Analysis</h3>
        <div class="template">
Compare the rhetorical strategies in [TEXT A] and [TEXT B].

Focus on:
- [SPECIFIC RHETORICAL ELEMENTS]
- How each text adapts to its audience and purpose
- Effectiveness of each approach

Which text is more persuasive for [SPECIFIC AUDIENCE]? Why?
        </div>

        <h3>Template 3: Critical Evaluation</h3>
        <div class="template">
Critically analyze [TEXT] for:
1. Rhetorical strengths and weaknesses
2. Logical fallacies or questionable reasoning
3. Assumptions and unstated premises
4. Bias or missing perspectives

Provide specific textual evidence for each point.
        </div>
    </div>

    <div class="section">
        <h2>Practice Exercise</h2>
        <p>Choose a text and write three different prompts for analyzing it:</p>

        <div class="question" style="margin: 20px 0;">
            <strong>Your text:</strong>
            <div style="border-bottom: 1px solid #ccc; min-height: 40px; margin: 10px 0;"></div>
        </div>

        <div class="question" style="margin: 20px 0;">
            <strong>Prompt 1 (Focus on rhetorical appeals):</strong>
            <div style="border-bottom: 1px solid #ccc; min-height: 60px; margin: 10px 0;"></div>
        </div>

        <div class="question" style="margin: 20px 0;">
            <strong>Prompt 2 (Focus on audience adaptation):</strong>
            <div style="border-bottom: 1px solid #ccc; min-height: 60px; margin: 10px 0;"></div>
        </div>

        <div class="question" style="margin: 20px 0;">
            <strong>Prompt 3 (Focus on argumentation structure):</strong>
            <div style="border-bottom: 1px solid #ccc; min-height: 60px; margin: 10px 0;"></div>
        </div>
    </div>

    <button class="no-print" onclick="window.print()" style="background: #8b5cf6; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; margin: 20px 0;">Print Worksheet</button>
</body>
</html>
    `;
}

/**
 * Generate Worksheet 3: Checklist for Evaluating AI Writing Assistance
 */
function generateWorksheet3() {
    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Checklist: Evaluating AI Writing Assistance</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; }
        h1 { color: #3b82f6; border-bottom: 3px solid #3b82f6; padding-bottom: 10px; }
        h2 { color: #2563eb; margin-top: 30px; }
        .section { background: #f9fafb; padding: 20px; margin: 20px 0; border-left: 4px solid #f59e0b; }
        .checklist { list-style: none; padding-left: 0; }
        .checklist li { padding: 10px; margin: 5px 0; background: white; border-radius: 5px; }
        .checklist input[type="checkbox"] { margin-right: 10px; transform: scale(1.2); }
        .category { background: #dbeafe; padding: 10px; margin: 15px 0; border-radius: 5px; font-weight: bold; }
        @media print { body { margin: 20px; } .no-print { display: none; } }
    </style>
</head>
<body>
    <h1>Checklist: Evaluating AI Writing Assistance</h1>
    <p><strong>Name:</strong> _____________________________ <strong>Date:</strong> _____________________</p>
    <p><strong>Assignment:</strong> _______________________________________________________________</p>

    <div class="section">
        <h2>Before Using AI</h2>
        <ul class="checklist">
            <li><input type="checkbox"> I understand the assignment requirements and expectations</li>
            <li><input type="checkbox"> I know what types of AI assistance are permitted for this assignment</li>
            <li><input type="checkbox"> I have reviewed my institution's AI use policy</li>
            <li><input type="checkbox"> I have done initial brainstorming and thinking on my own</li>
            <li><input type="checkbox"> I have a clear purpose for using AI (brainstorming, editing, research, etc.)</li>
        </ul>
    </div>

    <div class="section">
        <h2>During AI Use</h2>

        <div class="category">Accuracy & Quality</div>
        <ul class="checklist">
            <li><input type="checkbox"> I verified all factual claims made by the AI</li>
            <li><input type="checkbox"> I checked all citations and sources for accuracy</li>
            <li><input type="checkbox"> I identified any logical fallacies or weak reasoning</li>
            <li><input type="checkbox"> I assessed whether the AI's suggestions align with assignment goals</li>
        </ul>

        <div class="category">Critical Evaluation</div>
        <ul class="checklist">
            <li><input type="checkbox"> I identified potential biases in the AI's output</li>
            <li><input type="checkbox"> I considered what perspectives or voices might be missing</li>
            <li><input type="checkbox"> I evaluated whether the AI's suggestions match my own voice and style</li>
            <li><input type="checkbox"> I questioned the AI's assumptions and premises</li>
        </ul>

        <div class="category">Documentation</div>
        <ul class="checklist">
            <li><input type="checkbox"> I saved copies of prompts I used</li>
            <li><input type="checkbox"> I documented which parts of my work used AI assistance</li>
            <li><input type="checkbox"> I kept notes on how I modified or critiqued AI suggestions</li>
            <li><input type="checkbox"> I can explain my process if asked</li>
        </ul>
    </div>

    <div class="section">
        <h2>After Using AI</h2>

        <div class="category">Integration & Ownership</div>
        <ul class="checklist">
            <li><input type="checkbox"> I substantially revised and personalized any AI-generated content</li>
            <li><input type="checkbox"> The final work reflects my own understanding and voice</li>
            <li><input type="checkbox"> I can defend and explain all ideas in my work</li>
            <li><input type="checkbox"> I maintained critical distance rather than accepting AI output uncritically</li>
        </ul>

        <div class="category">Attribution & Ethics</div>
        <ul class="checklist">
            <li><input type="checkbox"> I properly attributed AI assistance according to course guidelines</li>
            <li><input type="checkbox"> I was transparent about my AI use where required</li>
            <li><input type="checkbox"> I did not misrepresent AI-generated content as entirely my own</li>
            <li><input type="checkbox"> I considered the ethical implications of my AI use</li>
        </ul>

        <div class="category">Learning & Reflection</div>
        <ul class="checklist">
            <li><input type="checkbox"> Using AI enhanced rather than replaced my learning</li>
            <li><input type="checkbox"> I developed my own skills through this process</li>
            <li><input type="checkbox"> I can articulate what I learned from using AI</li>
            <li><input type="checkbox"> I reflected on how AI use affected my thinking and writing process</li>
        </ul>
    </div>

    <div class="section">
        <h2>Reflection Questions</h2>
        <div style="margin: 20px 0;">
            <strong>1. How did AI assistance help or hinder your work on this assignment?</strong>
            <div style="border-bottom: 1px solid #ccc; min-height: 60px; margin: 10px 0;"></div>
        </div>
        <div style="margin: 20px 0;">
            <strong>2. What did you learn about AI's capabilities and limitations?</strong>
            <div style="border-bottom: 1px solid #ccc; min-height: 60px; margin: 10px 0;"></div>
        </div>
        <div style="margin: 20px 0;">
            <strong>3. How will you approach AI use differently in the future?</strong>
            <div style="border-bottom: 1px solid #ccc; min-height: 60px; margin: 10px 0;"></div>
        </div>
    </div>

    <button class="no-print" onclick="window.print()" style="background: #f59e0b; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; margin: 20px 0;">Print Checklist</button>
</body>
</html>
    `;
}

// Export functions for use in other modules if needed
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { openWorksheet };
}
